#!/usr/bin/env node
/* ─────────────────────────────────────────────────────────────
   Foundation · Emitter

   Turns the Tailwind-flavoured token source (tokens/*.css, authored as
   `@theme` blocks) into Tailwind-free outputs that a self-contained
   artifact can consume directly:

     dist/tokens.inline.css  — flat :root {…} + [data-theme="dark"] {…},
                               paste into an artifact <style>. No build,
                               no Tailwind, CSP-safe.
     dist/tokens.json        — { light: {token: value}, dark: {…} } for
                               artifact JS (Canvas/WebGL series colors etc.).

   The ONLY transform for the CSS path is `@theme {`/`@theme static {`
   → `:root {`. Everything else (var(), color-mix, the dark block, the
   reduced-motion media query) is already plain CSS and passes through.

   Generated files — never hand-edit dist/. Re-run `pnpm build`.
   ───────────────────────────────────────────────────────────── */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ICON_NAMES, VERSION as ICON_VERSION } from "../scripts/icon/registry.mjs";

// Order is readability-only; declarations merge regardless.
const LAYERS = [
  "palette",
  "surface",
  "typography",
  "elevation",
  "motion",
  "layout",
  "chart",
  "dark",
];

const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\n{3,}/g, "\n\n");
const themeToRoot = (css) => css.replace(/@theme\s+static\s*\{/g, ":root {").replace(/@theme\s*\{/g, ":root {");

// ── Exported token-emit functions (root is a directory containing tokens/) ──
const DECL = /--([\w-]+)\s*:\s*([^;{}]+);/g;
const collect = (css) => {
  const out = {};
  for (const [, name, value] of css.matchAll(DECL)) out[name] = value.trim().replace(/\s+/g, " ");
  return out;
};

export function emitInlineCss(root) {
  const header =
    "/* GENERATED by foundation/emit/build.mjs — DO NOT EDIT.\n" +
    "   Source of truth: foundation/tokens/*.css. Re-run `pnpm build`.\n" +
    "   Inline this whole block into a self-contained artifact's <style>. */\n\n";
  return header +
    LAYERS.map((name) => themeToRoot(stripComments(readFileSync(join(root, "tokens", `${name}.css`), "utf8"))).trim())
      .filter(Boolean).join("\n\n") + "\n";
}

export function emitTokensJson(root) {
  const light = {};
  for (const name of LAYERS) {
    if (name === "dark") continue;
    let css = stripComments(readFileSync(join(root, "tokens", `${name}.css`), "utf8"));
    // motion.css ends with a @media reduced-motion override — exclude it so the
    // light map keeps real durations, not the 0ms accessibility override.
    if (name === "motion") css = css.split("@media")[0];
    Object.assign(light, collect(css));
  }
  const dark = collect(stripComments(readFileSync(join(root, "tokens", "dark.css"), "utf8")));
  return { light, dark };
}

// ── CLI entry-point (write dist/ + catalog + console) ──────────────────────
if (fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const dist = join(root, "dist");

  // ── 1. dist/tokens.inline.css ──────────────────────────────────
  const inlineCss = emitInlineCss(root);

  mkdirSync(dist, { recursive: true });
  writeFileSync(join(dist, "tokens.inline.css"), inlineCss);

  // ── 2. dist/tokens.json ────────────────────────────────────────
  // Light = every --decl OUTSIDE the dark block and OUTSIDE @media.
  // Dark  = every --decl inside dark.css's [data-theme="dark"] block.
  const { light, dark } = emitTokensJson(root);

  writeFileSync(join(dist, "tokens.json"), JSON.stringify({ light, dark }, null, 2) + "\n");

  // ── 3. dist/catalog.json + dist/catalog.md ─────────────────────
  // The CLOSED SET an artifact may use, assembled FROM the sources so it can't
  // drift: token names (from the light map above), the exact class whitelist
  // (from the two reference CSS files), and a per-component index (one row per
  // contract *.md). Regenerated every build — never hand-maintained.

  // 3a. Exact class whitelist from a reference CSS file. Strip comments, then
  // remove every rule body (repeat for nested @media/@keyframes) so only selector
  // text remains — every `.x` left is a real, usable class.
  const classNamesFromCss = (css) => {
    let body = stripComments(css);
    let prev;
    do { prev = body; body = body.replace(/\{[^{}]*\}/g, " "); } while (body !== prev);
    const set = new Set();
    for (const m of body.matchAll(/\.(-?[A-Za-z_][\w-]*)/g)) set.add(m[1]);
    return set;
  };
  const cssClassNames = (file) => classNamesFromCss(readFileSync(file, "utf8"));
  const primCss = readFileSync(join(root, "primitives", "primitives.css"), "utf8");
  const compCss = readFileSync(join(root, "composites", "composites.css"), "utf8");
  const allClasses = [
    ...new Set([...classNamesFromCss(primCss), ...classNamesFromCss(compCss)]),
  ].sort();

  // 3a-bis. Per-component class lists, derived FROM the reference CSS (never from
  // hand-written prose). Each component owns the classes in its
  // `/* @component <slug> */` section (bounded by the ═══ section headers), plus
  // any BEM-namespaced class (slug / slug__x / slug--x) anywhere as a safety net.
  // One source, can't drift: the same CSS the closed set comes from.
  const SECTION_HEADER = /\/\*\s*═[^*]*\*\//g;
  const sectionClassMap = (css) => {
    const heads = [...css.matchAll(SECTION_HEADER)].map((m) => m.index);
    heads.push(css.length);
    const map = {};
    for (let i = 0; i < heads.length - 1; i++) {
      const section = css.slice(heads[i], heads[i + 1]);
      const marker = section.match(/@component\s+([a-z0-9 -]+?)\s*\*\//);
      if (!marker) continue;
      const classes = classNamesFromCss(section);
      // One shared section can serve several closely-related contracts (the date
      // pickers): `@component a b c` tags all of them.
      for (const slug of marker[1].trim().split(/\s+/)) {
        (map[slug] ||= new Set());
        for (const c of classes) map[slug].add(c);
      }
    }
    return map;
  };
  const sectionMaps = {
    primitives: sectionClassMap(primCss),
    composites: sectionClassMap(compCss),
  };
  const componentClasses = (slug, dir) => {
    const out = new Set(sectionMaps[dir]?.[slug] ?? []);
    for (const c of allClasses) {
      if (c === slug || c.startsWith(`${slug}__`) || c.startsWith(`${slug}--`)) out.add(c);
    }
    return [...out].sort().map((c) => `.${c}`);
  };

  // 3b. Per-component index from each contract *.md.
  const firstSentence = (body) => {
    // Join the first prose paragraph's wrapped lines, then clip to one sentence.
    let buf = "";
    for (const raw of body.split("\n")) {
      const line = raw.trim();
      if (!line || line.startsWith("#") || line.startsWith(">") || line.startsWith("```") || line.startsWith("|")) {
        if (buf) break;
        continue;
      }
      buf += (buf ? " " : "") + line;
      if (/[.。](\s|$)/.test(buf)) break;
    }
    const text = buf
      .replace(/`([^`]*)`/g, "$1")
      .replace(/\*\*?([^*]*)\*\*?/g, "$1")
      .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
    const m = text.match(/^(.*?[.。])(\s|$)/);
    return (m ? m[1] : text).trim();
  };
  const readComponents = (layer, dir) =>
    readdirSync(join(root, dir))
      .filter((f) => f.endsWith(".md"))
      .sort()
      .map((f) => {
        const name = f.replace(/\.md$/, "");
        const md = readFileSync(join(root, dir, f), "utf8");
        const h1 = (md.match(/^#\s+(.+)$/m) || [, name])[1].trim();
        const body = md.slice(md.indexOf("\n", md.search(/^#\s/m)) + 1);
        return {
          layer,
          name,
          title: h1,
          summary: firstSentence(body),
          contract: `${dir}/${f}`,
          example: existsSync(join(root, dir, `${name}.html`)) ? `${dir}/${name}.html` : null,
          // Patterns compose composites (listed in their contract), not raw classes.
          classes: layer === "pattern" ? [] : componentClasses(name, dir),
        };
      });
  const primitives = readComponents("primitive", "primitives");
  const composites = readComponents("composite", "composites");
  const patterns = readComponents("pattern", "patterns");
  const tokenNames = Object.keys(light).sort();

  const catalog = {
    generatedBy: "foundation/emit/build.mjs — DO NOT EDIT. Re-run `pnpm build`.",
    rule: "CLOSED SET for same-brand artifacts. Anything not here → governance/token-change.md.",
    tokens: tokenNames,
    classes: allClasses,
    primitives,
    composites,
    patterns,
  };
  writeFileSync(join(dist, "catalog.json"), JSON.stringify(catalog, null, 2) + "\n");

  // 3c. The human/agent-readable mirror.
  const esc = (s) => s.replace(/\|/g, "\\|");
  const rows = (list) =>
    list
      .map((c) => {
        const cls = c.classes.length ? c.classes.map((x) => `\`${x}\``).join(" ") : "—";
        const links = `[contract](../${c.contract})` + (c.example ? ` · [example](../${c.example})` : "");
        return `| \`${c.name}\` | ${esc(c.summary)} | ${esc(cls)} | ${links} |`;
      })
      .join("\n");
  const tokenGroups = {};
  for (const t of tokenNames) (tokenGroups[t.split("-")[0]] ||= []).push(t);
  const tokenLines = Object.keys(tokenGroups)
    .sort()
    .map((g) => `- **${g}** (${tokenGroups[g].length}) — ${tokenGroups[g].map((t) => `\`--${t}\``).join(" ")}`)
    .join("\n");

  const catalogMd = `# foundation · catalog — GENERATED, do not edit

> Rebuilt from the sources by \`pnpm build\` (machine mirror: \`catalog.json\`).
> This is the **closed set** a same-brand artifact may use. Anything not listed
> here is a contract gap → propose it via \`governance/token-change.md\` (tokens)
> or a primitive/composite contract PR. **Do not** hardcode hex/px or hand-roll a
> component that isn't here.
>
> Check an artifact against this set: \`node scripts/check-artifact.mjs <file.html>\`

## L1 · Tokens (${tokenNames.length})

Inline \`dist/tokens.inline.css\`, then reference as \`var(--name)\`. Values live in
that file / \`tokens.json\`; these are the legal **names**, grouped by prefix:

${tokenLines}

## L1.5 · Icons (${ICON_NAMES.length}, Lucide ${ICON_VERSION})

Icons are inline Lucide SVGs — raw material like tokens, **not** a class layer
(CSP blocks any icon font / sprite / CDN, so each icon is inlined). The full set
is not listed here; **never hand-write a path or invent a name** — query it and
paste the exact markup:

- find a name by meaning (English tags): \`node scripts/icon/icon.mjs search <intent>\`
- get the exact \`<svg>\`: \`node scripts/icon/icon.mjs get <name>\`

Every icon carries \`data-lucide="<name>"\` as its first attribute. The checker
rejects unknown names and altered paths; that same attribute is the Next.js
\`lucide-react\` bridge. Rules + React mapping: [\`primitives/icon.md\`](../primitives/icon.md).

## L2 · Primitives (${primitives.length}) — atoms

Classes in \`primitives/primitives.css\` (on top of the inlined tokens).

| component | use | classes (main; full set in \`catalog.json\`) | links |
|---|---|---|---|
${rows(primitives)}

## L2.5 · Composites (${composites.length}) — page building blocks

Classes in \`composites/composites.css\` (load after primitives — they reuse \`.btn\`/\`.input\`/…).

| component | use | classes (main; full set in \`catalog.json\`) | links |
|---|---|---|---|
${rows(composites)}

## L3 · Patterns (${patterns.length}) — assembled archetypes

A pattern is a named structure built from composites; copy its \`example\` and edit.

| pattern | use | composites used (see contract) | links |
|---|---|---|---|
${rows(patterns)}
`;
  writeFileSync(join(dist, "catalog.md"), catalogMd);

  console.log(`foundation: emitted dist/tokens.inline.css (${inlineCss.length} bytes)`);
  console.log(`foundation: emitted dist/tokens.json (light ${Object.keys(light).length} / dark ${Object.keys(dark).length} tokens)`);
  console.log(
    `foundation: emitted dist/catalog.json + catalog.md ` +
      `(${primitives.length} primitives, ${composites.length} composites, ${patterns.length} patterns, ` +
      `${allClasses.length} classes, ${tokenNames.length} tokens)`,
  );
}
