#!/usr/bin/env node
/* ---------------------------------------------------------------------------
   Foundation · Emitter

   Turns the Tailwind-flavoured token source (tokens/*.css, authored as
   `@theme` blocks) into Tailwind-free snapshot files:

     build/current/tokens.inline.css  — generated current-source token CSS
                                        for prototype preview.
     build/current/primitives.css     — generated current-source primitive CSS.
     build/current/composites.css     — generated current-source composite CSS.
     release/*                       — committed current artifact snapshot.

   The ONLY transform for the CSS path is `@theme {`/`@theme static {`
   -> `:root {`. Everything else (var(), color-mix, the dark block, the
   reduced-motion media query) is already plain CSS and passes through.

   Generated snapshot files are never hand-edited. Re-run `pnpm build`.
   Numbered versions/vN directories are saved prototype snapshots and are not
   rewritten by the emitter.
   --------------------------------------------------------------------------- */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { ICON_NAMES, VERSION as ICON_VERSION } from "../scripts/icon/registry.mjs";
import { GOVERNED_SOURCE_PATHS } from "../scripts/source-git.mjs";

export const CURRENT_VERSION = "current";
export const CURRENT_BUILD_ROOT = "build";
export const RELEASE_STRUCTURE = [
  "catalog.json",
  "catalog.md",
  "tokens.inline.css",
  "tokens.json",
  "composites.css",
  "manifest.json",
];

// Order is readability-only; declarations merge regardless.
const LAYERS = [
  "palette",
  "surface",
  "typography",
  "elevation",
  "motion",
  "layout",
  "chart",
  "dark",
];

const stripComments = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\n{3,}/g, "\n\n");
const themeToRoot = (css) => css.replace(/@theme\s+static\s*\{/g, ":root {").replace(/@theme\s*\{/g, ":root {");
const escapeRegExp = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const DECL = /--([\w-]+)\s*:\s*([^;{}]+);/g;
const collect = (css) => {
  const out = {};
  for (const [, name, value] of css.matchAll(DECL)) out[name] = value.trim().replace(/\s+/g, " ");
  return out;
};

export function emitInlineCss(root) {
  const header =
    "/* GENERATED by foundation/emit/build.mjs - DO NOT EDIT.\n" +
    "   Source of truth: foundation/tokens/*.css. Re-run `pnpm build`.\n" +
    "   Inline this whole block into a self-contained artifact's <style>. */\n\n";
  return header +
    LAYERS.map((name) => themeToRoot(stripComments(readFileSync(join(root, "tokens", `${name}.css`), "utf8"))).trim())
      .filter(Boolean).join("\n\n") + "\n";
}

export function emitTokensJson(root) {
  const light = {};
  for (const name of LAYERS) {
    if (name === "dark") continue;
    let css = stripComments(readFileSync(join(root, "tokens", `${name}.css`), "utf8"));
    // motion.css ends with a @media reduced-motion override. Exclude it so the
    // light map keeps real durations, not the 0ms accessibility override.
    if (name === "motion") css = css.split("@media")[0];
    Object.assign(light, collect(css));
  }
  const dark = collect(stripComments(readFileSync(join(root, "tokens", "dark.css"), "utf8")));
  return { light, dark };
}

export function applyTokenJsonOverrides(tokenJson, tokenOverrides = {}) {
  const next = JSON.parse(JSON.stringify(tokenJson));
  for (const [tokenName, value] of Object.entries(tokenOverrides)) {
    const key = tokenName.replace(/^--/, "");
    let wrote = false;
    for (const group of Object.values(next)) {
      if (group && typeof group === "object" && Object.prototype.hasOwnProperty.call(group, key)) {
        group[key] = value;
        wrote = true;
      }
    }
    if (!wrote) {
      next.light = next.light || {};
      next.light[key] = value;
    }
  }
  return next;
}

export function applyTokenCssOverrides(css, tokenOverrides = {}) {
  let nextCss = css;
  const appended = [];
  for (const name of Object.keys(tokenOverrides).sort()) {
    const value = tokenOverrides[name];
    const re = new RegExp(`(^[ \\t]*${escapeRegExp(name)}\\s*:\\s*)([^;]*)(;)`, "m");
    let found = false;
    nextCss = nextCss.replace(re, (_match, prefix, _oldValue, suffix) => {
      found = true;
      return `${prefix}${value}${suffix}`;
    });
    if (!found) appended.push([name, value]);
  }
  if (appended.length) {
    nextCss = `${nextCss.trimEnd()}\n\n:root {\n${appended.map(([name, value]) => `  ${name}: ${value};`).join("\n")}\n}\n`;
  }
  return `${nextCss.trimEnd()}\n`;
}

export function appendCompositeOverrides(css, classOverrides = {}, meta = {}) {
  const selectors = Object.keys(classOverrides).sort();
  const lines = [
    "",
    "/* Prototype published overrides",
    `   Version: ${meta.version || ""}`,
    `   Source page: ${meta.page || ""}`,
    `   Published: ${meta.publishedAt || ""}`,
    "*/",
  ];
  if (!selectors.length) {
    lines.push("/* No composite class overrides in this snapshot. */");
  }
  for (const selector of selectors) {
    lines.push(`${selector} {`);
    for (const prop of Object.keys(classOverrides[selector]).sort()) {
      lines.push(`  ${prop}: ${classOverrides[selector][prop]};`);
    }
    lines.push("}", "");
  }
  return `${css.trimEnd()}\n${lines.join("\n").trimEnd()}\n`;
}

function classNamesFromCss(css) {
  let body = stripComments(css);
  let prev;
  do {
    prev = body;
    body = body.replace(/\{[^{}]*\}/g, " ");
  } while (body !== prev);
  const set = new Set();
  for (const m of body.matchAll(/\.(-?[A-Za-z_][\w-]*)/g)) set.add(m[1]);
  return set;
}

// Per-component class lists are derived from the reference CSS, not from
// hand-written prose. A component owns classes in its `@component <slug>`
// section, plus any BEM-namespaced class as a safety net.
const SECTION_HEADER = /\/\*\s*═[^*]*\*\//g;
function sectionClassMap(css) {
  const heads = [...css.matchAll(SECTION_HEADER)].map((m) => m.index);
  heads.push(css.length);
  const map = {};
  for (let i = 0; i < heads.length - 1; i++) {
    const section = css.slice(heads[i], heads[i + 1]);
    const marker = section.match(/@component\s+([a-z0-9 -]+?)\s*\*\//);
    if (!marker) continue;
    const classes = classNamesFromCss(section);
    for (const slug of marker[1].trim().split(/\s+/)) {
      (map[slug] ||= new Set());
      for (const c of classes) map[slug].add(c);
    }
  }
  return map;
}

function firstSentence(body) {
  let buf = "";
  for (const raw of body.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#") || line.startsWith(">") || line.startsWith("```") || line.startsWith("|")) {
      if (buf) break;
      continue;
    }
    buf += (buf ? " " : "") + line;
    if (/[.。](\s|$)/.test(buf)) break;
  }
  const text = buf
    .replace(/`([^`]*)`/g, "$1")
    .replace(/\*\*?([^*]*)\*\*?/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1");
  const m = text.match(/^(.*?[.。])(\s|$)/);
  return (m ? m[1] : text).trim();
}

function readComponents(root, layer, dir, componentClasses) {
  return readdirSync(join(root, dir))
    .filter((f) => f.endsWith(".md"))
    .sort()
    .map((f) => {
      const name = f.replace(/\.md$/, "");
      const md = readFileSync(join(root, dir, f), "utf8");
      const h1 = (md.match(/^#\s+(.+)$/m) || [, name])[1].trim();
      const body = md.slice(md.indexOf("\n", md.search(/^#\s/m)) + 1);
      return {
        layer,
        name,
        title: h1,
        summary: firstSentence(body),
        contract: `${dir}/${f}`,
        example: existsSync(join(root, dir, `${name}.html`)) ? `${dir}/${name}.html` : null,
        // Patterns compose composites (listed in their contract), not raw classes.
        classes: layer === "pattern" ? [] : componentClasses(name, dir),
      };
    });
}

export function emitCatalog(root) {
  const { light } = emitTokensJson(root);
  const primCss = readFileSync(join(root, "primitives", "primitives.css"), "utf8");
  const compCss = readFileSync(join(root, "composites", "composites.css"), "utf8");
  const allClasses = [
    ...new Set([...classNamesFromCss(primCss), ...classNamesFromCss(compCss)]),
  ].sort();
  const sectionMaps = {
    primitives: sectionClassMap(primCss),
    composites: sectionClassMap(compCss),
  };
  const componentClasses = (slug, dir) => {
    const out = new Set(sectionMaps[dir]?.[slug] ?? []);
    for (const c of allClasses) {
      if (c === slug || c.startsWith(`${slug}__`) || c.startsWith(`${slug}--`)) out.add(c);
    }
    return [...out].sort().map((c) => `.${c}`);
  };
  const primitives = readComponents(root, "primitive", "primitives", componentClasses);
  const composites = readComponents(root, "composite", "composites", componentClasses);
  const patterns = readComponents(root, "pattern", "patterns", componentClasses);
  const tokenNames = Object.keys(light).sort();

  return {
    generatedBy: "foundation/emit/build.mjs - DO NOT EDIT. Re-run `pnpm build`.",
    rule: "CLOSED SET for same-brand artifacts. Anything not here -> governance/token-change.md.",
    tokens: tokenNames,
    classes: allClasses,
    primitives,
    composites,
    patterns,
  };
}

export function emitCatalogMarkdown(catalog) {
  const { tokens: tokenNames, classes: allClasses, primitives, composites, patterns } = catalog;
  const esc = (s) => s.replace(/\|/g, "\\|");
  const rows = (list) =>
    list
      .map((c) => {
        const cls = c.classes.length ? c.classes.map((x) => `\`${x}\``).join(" ") : "-";
        const links = `[contract](../${c.contract})` + (c.example ? ` · [example](../${c.example})` : "");
        return `| \`${c.name}\` | ${esc(c.summary)} | ${esc(cls)} | ${links} |`;
      })
      .join("\n");
  const tokenGroups = {};
  for (const t of tokenNames) (tokenGroups[t.split("-")[0]] ||= []).push(t);
  const tokenLines = Object.keys(tokenGroups)
    .sort()
    .map((g) => `- **${g}** (${tokenGroups[g].length}) - ${tokenGroups[g].map((t) => `\`--${t}\``).join(" ")}`)
    .join("\n");

  return `# foundation · catalog - GENERATED, do not edit

> Rebuilt from the sources by \`pnpm build\` (machine mirror: \`catalog.json\`).
> This is the **closed set** a same-brand artifact may use. Anything not listed
> here is a contract gap -> propose it via \`governance/token-change.md\` (tokens)
> or a primitive/composite contract PR. **Do not** hardcode hex/px or hand-roll a
> component that isn't here.
>
> Check an artifact against this set: \`node scripts/check-artifact.mjs <file.html>\`

## L1 · Tokens (${tokenNames.length})

Inline \`tokens.inline.css\`, then reference as \`var(--name)\`. Values live in
that file / \`tokens.json\`; these are the legal **names**, grouped by prefix:

${tokenLines}

## L1.5 · Icons (${ICON_NAMES.length}, Lucide ${ICON_VERSION})

Icons are inline Lucide SVGs - raw material like tokens, **not** a class layer
(CSP blocks any icon font / sprite / CDN, so each icon is inlined). The full set
is not listed here; **never hand-write a path or invent a name** - query it and
paste the exact markup:

- find a name by meaning (English tags): \`node scripts/icon/icon.mjs search <intent>\`
- get the exact \`<svg>\`: \`node scripts/icon/icon.mjs get <name>\`

Every icon carries \`data-lucide="<name>"\` as its first attribute. The checker
rejects unknown names and altered paths; that same attribute is the Next.js
\`lucide-react\` bridge. Rules + React mapping: [\`primitives/icon.md\`](../primitives/icon.md).

## L2 · Primitives (${primitives.length}) - atoms

Classes in \`primitives/primitives.css\` (on top of the inlined tokens).

| component | use | classes (main; full set in \`catalog.json\`) | links |
|---|---|---|---|
${rows(primitives)}

## L2.5 · Composites (${composites.length}) - page building blocks

Classes in \`composites.css\` (load after primitives - they reuse \`.btn\`/\`.input\`/...).

| component | use | classes (main; full set in \`catalog.json\`) | links |
|---|---|---|---|
${rows(composites)}

## L3 · Patterns (${patterns.length}) - assembled archetypes

A pattern is a named structure built from composites; copy its \`example\` and edit.

| pattern | use | composites used (see contract) | links |
|---|---|---|---|
${rows(patterns)}
`;
}

function currentManifest() {
  const sourceGit = {
    available: false,
    commit: "",
    shortCommit: "",
    dirty: false,
    dirtyPaths: [],
    restorePaths: [...GOVERNED_SOURCE_PATHS],
  };
  return {
    version: CURRENT_VERSION,
    baseVersion: "",
    publishedAt: "",
    source: {
      page: "foundation-current",
      title: "Foundation current source",
      href: "",
    },
    counts: {
      tokens: 0,
      compositeDeclarations: 0,
      selectors: 0,
      elementPaths: 0,
    },
    changedTokens: [],
    tokenOverrides: {},
    classOverrides: {},
    changes: {
      tokens: [],
      composites: [],
    },
    elementOverrides: {},
    conflicts: [],
    skipped: {
      tokens: [],
      classOverrides: [],
    },
    sourceCommit: sourceGit.commit || "",
    sourceDirty: Boolean(sourceGit.dirty),
    sourceGit,
    current: true,
  };
}

export function writeCurrentVersion(root, options = {}) {
  const versionDir = join(root, CURRENT_BUILD_ROOT, CURRENT_VERSION);
  mkdirSync(versionDir, { recursive: true });
  const inlineCss = emitInlineCss(root);
  writeFileSync(join(versionDir, "tokens.inline.css"), inlineCss, "utf8");
  copyFileSync(join(root, "primitives", "primitives.css"), join(versionDir, "primitives.css"));
  copyFileSync(join(root, "composites", "composites.css"), join(versionDir, "composites.css"));
  writeFileSync(join(versionDir, "manifest.json"), `${JSON.stringify(currentManifest(root, options), null, 2)}\n`, "utf8");
  return {
    versionDir,
    inlineCss,
  };
}

export function refreshReleaseMetadata(root) {
  const releaseDir = join(root, "release");
  mkdirSync(releaseDir, { recursive: true });

  const manifestPath = join(releaseDir, "manifest.json");
  const manifest = existsSync(manifestPath)
    ? JSON.parse(readFileSync(manifestPath, "utf8"))
    : {
        ...currentManifest(root),
        releasedAt: "",
        release: {
          version: CURRENT_VERSION,
          structure: RELEASE_STRUCTURE,
        },
      };
  if (!existsSync(manifestPath)) {
    writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, "utf8");
  }

  const catalog = emitCatalog(root);
  const releaseVersion = manifest.release?.version || manifest.version || CURRENT_VERSION;
  const tokenCss = applyTokenCssOverrides(emitInlineCss(root), manifest.tokenOverrides || {});
  const compositeCss = appendCompositeOverrides(
    readFileSync(join(root, "composites", "composites.css"), "utf8"),
    manifest.classOverrides || {},
    {
      version: releaseVersion,
      page: manifest.source?.page || "",
      publishedAt: manifest.publishedAt || "",
    },
  );
  const tokenJson = applyTokenJsonOverrides(emitTokensJson(root), manifest.tokenOverrides || {});
  writeFileSync(join(releaseDir, "tokens.inline.css"), tokenCss, "utf8");
  writeFileSync(join(releaseDir, "composites.css"), compositeCss, "utf8");
  writeFileSync(join(releaseDir, "catalog.json"), `${JSON.stringify(catalog, null, 2)}\n`, "utf8");
  writeFileSync(join(releaseDir, "catalog.md"), emitCatalogMarkdown(catalog), "utf8");
  writeFileSync(join(releaseDir, "tokens.json"), `${JSON.stringify(tokenJson, null, 2)}\n`, "utf8");

  return { releaseDir, catalog, tokenJson, manifest };
}

if (fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = join(dirname(fileURLToPath(import.meta.url)), "..");
  const { inlineCss } = writeCurrentVersion(root);
  const { catalog, tokenJson } = refreshReleaseMetadata(root);

  console.log(`foundation: emitted ${CURRENT_BUILD_ROOT}/${CURRENT_VERSION}/tokens.inline.css (${inlineCss.length} bytes)`);
  console.log(`foundation: emitted ${CURRENT_BUILD_ROOT}/${CURRENT_VERSION}/primitives.css`);
  console.log(`foundation: emitted ${CURRENT_BUILD_ROOT}/${CURRENT_VERSION}/composites.css`);
  console.log(
    `foundation: refreshed release/catalog.json + catalog.md ` +
      `(${catalog.primitives.length} primitives, ${catalog.composites.length} composites, ` +
      `${catalog.patterns.length} patterns, ${catalog.classes.length} classes, ${catalog.tokens.length} tokens)`,
  );
  console.log(
    `foundation: refreshed release/tokens.json ` +
      `(light ${Object.keys(tokenJson.light).length} / dark ${Object.keys(tokenJson.dark).length} tokens)`,
  );
}
